Repository CSC207-2022F-UofT/course-project-group-140-q-a-forum, pull requests merged in 2022-11, with the labels that each got.

#51 MAJOR UPDATE
  .idea/misc.xml
  build.gradle
  gradlew
  gradlew.bat
  src/database/DataHandlerInterface.java
  src/database/DatabaseDataHandler.java
  src/database/RuntimeDataHandler.java
Labels: bug, enhancement, Controller, Interface, Essentials

#54 [+] Introduction of the data base gateway for access to data.
  src/database/DataHandlerInterface.java
  src/database/DatabaseDataHandler.java
  src/database/DatabaseGateway.java
  src/database/RuntimeDataHandler.java
  src/main.java
  src/use_cases/CourseUseCaseInteractor.java
  src/use_cases/DataBaseAccess/CourseDataInterface.java
  src/use_cases/DataBaseAccess/DataInterface.java
  src/use_cases/DataBaseAccess/PostDataInterface.java
  src/use_cases/DataBaseAccess/ReportDataInterface.java
  src/use_cases/DataBaseAccess/UserDataInterface.java
  src/use_cases/ReportUseCaseInteractor.java
  src/use_cases/UserUseCaseInteractor.java
Labels: bug, Entities, Essentials

#56 [*] Reorganized file formatting and strcture of the whole project
  .gitignore
  .idea/.name
  .idea/misc.xml
  .idea/vcs.xml
  README.md
  ScreenShot/ChangePassWordForm.png
  ScreenShot/LoginForm.png
  ScreenShot/MainForm(showingContent)/CommentsForm.png
  ScreenShot/MainForm(showingContent)/CoursesForm.png
  ScreenShot/MainForm(showingContent)/PostForm.png
  ScreenShot/ProfilePage.png
  ScreenShot/RegisterForm/MakeAComment.png
  ScreenShot/RegisterForm/MakeACourse.png
  ScreenShot/RegisterForm/MakeAPost.png
  ScreenShot/RegisterForm/MakeAReport.png
  ScreenShot/RegisterForm/RegisterACourse.png
  ScreenShot/RegisterForm/RegisterAUser.png
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/UseCases/CourseUseCaseInteractor.java
  src/UseCases/DataBaseAccess/CourseDataInterface.java
  src/UseCases/DataBaseAccess/DataInterface.java
  src/UseCases/DataBaseAccess/LoginDataInterface.java
  src/UseCases/DataBaseAccess/PostDataInterface.java
  src/UseCases/DataBaseAccess/ReportDataInterface.java
  src/UseCases/DataBaseAccess/UserDataInterface.java
  src/UseCases/LoginUseCaseInteractor.java
  src/UseCases/PostUseCaseInteractor.java
  src/UseCases/ReportUseCaseInteractor.java
  src/UseCases/UserUseCaseInteractor.java
  src/controllers/CourseController.java
  src/controllers/PostControllers.java
  src/controllers/ReportController.java
  src/controllers/UserController.java
Labels: documentation

#63 Fixing some bugs in post and course entities, and usecases.
  src/entities/Comment.java
  src/entities/Course.java
  src/entities/Post.java
  src/use_cases/PostUseCaseInteractor.java
Labels: bug

#64 [+] JUST RESOLVED THE EXCEPTION PROBLEM
  src/use_cases/UserUseCaseInteractor.java
Labels: bug
